"""Renomeia Observation de pessoa para ErpPersonObservation

Revision ID: 0f8613715f23
Revises: d65d20b022a4
Create Date: 2025-04-02 07:12:08.472489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f8613715f23'
down_revision: Union[str, None] = 'd65d20b022a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
