"""Initial schema setup based on ORM models

Revision ID: 1b03d6b18412
Revises: 
Create Date: 2025-04-01 22:16:51.405386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b03d6b18412'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_product_observations_ref_code', table_name='product_observations')
    op.drop_index('idx_product_observations_resolved_timestamp', table_name='product_observations')
    op.create_index(op.f('ix_product_observations_reference_code'), 'product_observations', ['reference_code'], unique=False)
    op.create_index(op.f('ix_product_observations_resolved'), 'product_observations', ['resolved'], unique=False)
    op.drop_index('idx_user_permissions_user_id', table_name='user_permissions')
    op.drop_constraint('user_permissions_user_id_key', 'user_permissions', type_='unique')
    op.create_index(op.f('ix_user_permissions_user_id'), 'user_permissions', ['user_id'], unique=True)
    op.drop_index('idx_users_email', table_name='users')
    op.drop_index('idx_users_email_lower', table_name='users')
    op.drop_index('idx_users_username', table_name='users')
    op.drop_index('idx_users_username_lower', table_name='users')
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_constraint('users_username_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.create_index('idx_users_username_lower', 'users', [sa.text('lower(username)')], unique=False)
    op.create_index('idx_users_username', 'users', ['username'], unique=False)
    op.create_index('idx_users_email_lower', 'users', [sa.text('lower(email)')], unique=False)
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.drop_index(op.f('ix_user_permissions_user_id'), table_name='user_permissions')
    op.create_unique_constraint('user_permissions_user_id_key', 'user_permissions', ['user_id'])
    op.create_index('idx_user_permissions_user_id', 'user_permissions', ['user_id'], unique=False)
    op.drop_index(op.f('ix_product_observations_resolved'), table_name='product_observations')
    op.drop_index(op.f('ix_product_observations_reference_code'), table_name='product_observations')
    op.create_index('idx_product_observations_resolved_timestamp', 'product_observations', ['resolved', 'timestamp'], unique=False)
    op.create_index('idx_product_observations_ref_code', 'product_observations', ['reference_code'], unique=False)
    # ### end Alembic commands ###
