"""Adiciona tabelas de cache para dados de Pessoa do ERP

Revision ID: d65d20b022a4
Revises: 1b03d6b18412
Create Date: 2025-04-02 00:13:59.679043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd65d20b022a4'
down_revision: Union[str, None] = '1b03d6b18412'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('erp_persons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('erp_code', sa.Integer(), nullable=False, comment='Código da pessoa no ERP (ex: individuals.items[0].code).'),
    sa.Column('person_type', sa.CHAR(length=2), nullable=False, comment="Tipo de Pessoa: 'PF' (Física) ou 'PJ' (Jurídica)."),
    sa.Column('name', sa.Text(), nullable=False, comment='Nome (PF) ou Razão Social (PJ) da pessoa no ERP.'),
    sa.Column('is_inactive', sa.Boolean(), nullable=False, comment="Indica se a pessoa está inativa no ERP (campo 'isInactive')."),
    sa.Column('is_customer', sa.Boolean(), nullable=True, comment="Flag 'isCustomer' do ERP."),
    sa.Column('is_supplier', sa.Boolean(), nullable=True, comment="Flag 'isSupplier' do ERP."),
    sa.Column('is_representative', sa.Boolean(), nullable=True, comment="Flag 'isRepresentative' do ERP."),
    sa.Column('is_employee', sa.Boolean(), nullable=True, comment="Flag 'isEmployee' do ERP (principalmente PF)."),
    sa.Column('customer_status', sa.String(length=50), nullable=True, comment="Status do cliente no ERP (campo 'customerStatus')."),
    sa.Column('employee_status', sa.String(length=50), nullable=True, comment="Status do funcionário no ERP (campo 'employeeStatus', apenas PF)."),
    sa.Column('erp_insert_date', sa.TIMESTAMP(timezone=True), nullable=True, comment="Data de inserção original no ERP (campo 'insertDate')."),
    sa.Column('erp_change_date', sa.TIMESTAMP(timezone=True), nullable=True, comment="Data da última alteração no ERP (campo 'maxChangeFilterDate'). Usado para sync incremental."),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp da criação do registro no cache local.'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp da última atualização do registro no cache local.'),
    sa.Column('last_sync_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='Timestamp da última sincronização bem-sucedida com o ERP para este registro.'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_erp_persons'))
    )
    op.create_index(op.f('ix_erp_persons_erp_change_date'), 'erp_persons', ['erp_change_date'], unique=False)
    op.create_index(op.f('ix_erp_persons_erp_code'), 'erp_persons', ['erp_code'], unique=True)
    op.create_index('ix_erp_persons_erp_code_type', 'erp_persons', ['erp_code', 'person_type'], unique=False)
    op.create_index(op.f('ix_erp_persons_is_inactive'), 'erp_persons', ['is_inactive'], unique=False)
    op.create_index(op.f('ix_erp_persons_last_sync_at'), 'erp_persons', ['last_sync_at'], unique=False)
    op.create_index(op.f('ix_erp_persons_person_type'), 'erp_persons', ['person_type'], unique=False)
    op.create_table('erp_individual_details',
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False, comment="CPF do indivíduo (campo 'cpf')."),
    sa.Column('rg', sa.String(length=30), nullable=True, comment="RG do indivíduo (campo 'rg')."),
    sa.Column('rg_federal_agency', sa.String(length=20), nullable=True, comment="Órgão emissor do RG (campo 'rgFederalAgency')."),
    sa.Column('birth_date', sa.Date(), nullable=True, comment="Data de nascimento (campo 'birthDate')."),
    sa.Column('marital_status', sa.String(length=20), nullable=True, comment="Estado civil (campo 'maritalStatus')."),
    sa.Column('gender', sa.String(length=20), nullable=True, comment="Gênero (campo 'gender')."),
    sa.Column('mother_name', sa.Text(), nullable=True, comment="Nome da mãe (campo 'motherName')."),
    sa.Column('father_name', sa.Text(), nullable=True, comment="Nome do pai (campo 'fatherName')."),
    sa.Column('nationality', sa.String(length=50), nullable=True, comment="Nacionalidade (campo 'nationality')."),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp da criação do registro no cache local.'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp da última atualização do registro no cache local.'),
    sa.Column('last_sync_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='Timestamp da última sincronização bem-sucedida com o ERP para este registro.'),
    sa.ForeignKeyConstraint(['person_id'], ['erp_persons.id'], name=op.f('fk_erp_individual_details_person_id_erp_persons'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('person_id', name=op.f('pk_erp_individual_details'))
    )
    op.create_index(op.f('ix_erp_individual_details_cpf'), 'erp_individual_details', ['cpf'], unique=True)
    op.create_index(op.f('ix_erp_individual_details_last_sync_at'), 'erp_individual_details', ['last_sync_at'], unique=False)
    op.create_table('erp_legal_entity_details',
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('cnpj', sa.String(length=14), nullable=False, comment="CNPJ da entidade (campo 'cnpj')."),
    sa.Column('fantasy_name', sa.Text(), nullable=True, comment="Nome Fantasia (campo 'fantasyName')."),
    sa.Column('state_registration', sa.String(length=30), nullable=True, comment="Inscrição Estadual (campo 'numberStateRegistration')."),
    sa.Column('state_registration_uf', sa.String(length=2), nullable=True, comment="UF da Inscrição Estadual (campo 'uf')."),
    sa.Column('foundation_date', sa.Date(), nullable=True, comment="Data de fundação (campo 'dateFoundation')."),
    sa.Column('municipal_registration', sa.String(length=30), nullable=True, comment="Inscrição Municipal (campo 'registrationMunicipal')."),
    sa.Column('share_capital', sa.NUMERIC(precision=18, scale=2), nullable=True, comment="Capital Social (campo 'shareCapital')."),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp da criação do registro no cache local.'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp da última atualização do registro no cache local.'),
    sa.Column('last_sync_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='Timestamp da última sincronização bem-sucedida com o ERP para este registro.'),
    sa.ForeignKeyConstraint(['person_id'], ['erp_persons.id'], name=op.f('fk_erp_legal_entity_details_person_id_erp_persons'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('person_id', name=op.f('pk_erp_legal_entity_details'))
    )
    op.create_index(op.f('ix_erp_legal_entity_details_cnpj'), 'erp_legal_entity_details', ['cnpj'], unique=True)
    op.create_index(op.f('ix_erp_legal_entity_details_last_sync_at'), 'erp_legal_entity_details', ['last_sync_at'], unique=False)
    op.create_table('erp_person_additional_fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('erp_field_code', sa.Integer(), nullable=False, comment="Código do campo adicional no ERP (campo 'code')."),
    sa.Column('erp_field_name', sa.String(length=100), nullable=True, comment="Nome do campo adicional no ERP (campo 'name')."),
    sa.Column('erp_field_type', sa.String(length=20), nullable=True, comment="Tipo do campo adicional no ERP (campo 'type', ex: String)."),
    sa.Column('value', sa.Text(), nullable=True, comment="Valor do campo adicional (campo 'value')."),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp da criação do registro no cache local.'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp da última atualização do registro no cache local.'),
    sa.Column('last_sync_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='Timestamp da última sincronização bem-sucedida com o ERP para este registro.'),
    sa.ForeignKeyConstraint(['person_id'], ['erp_persons.id'], name=op.f('fk_erp_person_additional_fields_person_id_erp_persons'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_erp_person_additional_fields')),
    sa.UniqueConstraint('person_id', 'erp_field_code', name='uq_person_additional_field')
    )
    op.create_index(op.f('ix_erp_person_additional_fields_last_sync_at'), 'erp_person_additional_fields', ['last_sync_at'], unique=False)
    op.create_index(op.f('ix_erp_person_additional_fields_person_id'), 'erp_person_additional_fields', ['person_id'], unique=False)
    op.create_table('erp_person_addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('erp_sequence_code', sa.Integer(), nullable=True, comment='Código de sequência do endereço no ERP.'),
    sa.Column('address_type', sa.String(length=50), nullable=True, comment="Tipo de endereço (campo 'addressType', ex: Commercial)."),
    sa.Column('public_place', sa.Text(), nullable=True, comment="Logradouro (campo 'publicPlace')."),
    sa.Column('address_detail', sa.Text(), nullable=True, comment="Endereço (complemento do logradouro, campo 'address')."),
    sa.Column('number', sa.String(length=20), nullable=True, comment="Número (campo 'addressNumber')."),
    sa.Column('complement', sa.Text(), nullable=True, comment="Complemento (campo 'complement')."),
    sa.Column('neighborhood', sa.String(length=100), nullable=True, comment="Bairro (campo 'neighborhood')."),
    sa.Column('city_name', sa.String(length=100), nullable=True, comment="Nome da cidade (campo 'cityName')."),
    sa.Column('state_abbreviation', sa.String(length=2), nullable=True, comment="Sigla do estado (campo 'stateAbbreviation')."),
    sa.Column('zip_code', sa.String(length=10), nullable=True, comment="CEP (campo 'cep')."),
    sa.Column('country_name', sa.String(length=50), nullable=True, comment="Nome do país (campo 'countryName')."),
    sa.Column('reference', sa.Text(), nullable=True, comment="Ponto de referência (campo 'reference')."),
    sa.Column('is_default', sa.Boolean(), nullable=False, comment='Indica se este é o endereço padrão (lógica de sync pode definir).'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp da criação do registro no cache local.'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp da última atualização do registro no cache local.'),
    sa.Column('last_sync_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='Timestamp da última sincronização bem-sucedida com o ERP para este registro.'),
    sa.ForeignKeyConstraint(['person_id'], ['erp_persons.id'], name=op.f('fk_erp_person_addresses_person_id_erp_persons'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_erp_person_addresses')),
    sa.UniqueConstraint('person_id', 'erp_sequence_code', name='uq_person_address_sequence')
    )
    op.create_index(op.f('ix_erp_person_addresses_last_sync_at'), 'erp_person_addresses', ['last_sync_at'], unique=False)
    op.create_index(op.f('ix_erp_person_addresses_person_id'), 'erp_person_addresses', ['person_id'], unique=False)
    op.create_index(op.f('ix_erp_person_addresses_zip_code'), 'erp_person_addresses', ['zip_code'], unique=False)
    op.create_table('erp_person_classifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('type_code', sa.Integer(), nullable=False, comment="Código do tipo de classificação no ERP (campo 'typeCode')."),
    sa.Column('type_name', sa.String(length=100), nullable=True, comment="Nome do tipo de classificação (campo 'typeName')."),
    sa.Column('code', sa.String(length=50), nullable=False, comment="Código da classificação dentro do tipo (campo 'code')."),
    sa.Column('name', sa.String(length=100), nullable=True, comment="Nome da classificação (campo 'name')."),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp da criação do registro no cache local.'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp da última atualização do registro no cache local.'),
    sa.Column('last_sync_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='Timestamp da última sincronização bem-sucedida com o ERP para este registro.'),
    sa.ForeignKeyConstraint(['person_id'], ['erp_persons.id'], name=op.f('fk_erp_person_classifications_person_id_erp_persons'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_erp_person_classifications')),
    sa.UniqueConstraint('person_id', 'type_code', 'code', name='uq_person_classification')
    )
    op.create_index(op.f('ix_erp_person_classifications_last_sync_at'), 'erp_person_classifications', ['last_sync_at'], unique=False)
    op.create_index(op.f('ix_erp_person_classifications_person_id'), 'erp_person_classifications', ['person_id'], unique=False)
    op.create_table('erp_person_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('erp_sequence_code', sa.Integer(), nullable=True, comment='Código de sequência do contato no ERP.'),
    sa.Column('name', sa.Text(), nullable=True, comment="Nome do contato (campo 'name')."),
    sa.Column('type_name', sa.String(length=50), nullable=True, comment="Tipo do contato (campo 'typeName')."),
    sa.Column('function', sa.String(length=100), nullable=True, comment="Função/Cargo do contato (campo 'function')."),
    sa.Column('phone_number', sa.String(length=30), nullable=True, comment="Telefone do contato (campo 'phoneNumber')."),
    sa.Column('cell_number', sa.String(length=30), nullable=True, comment="Celular do contato (campo 'cellNumber')."),
    sa.Column('email', sa.String(length=255), nullable=True, comment="Email do contato (campo 'email')."),
    sa.Column('birth_date', sa.Date(), nullable=True, comment="Data de nascimento do contato (campo 'birthDate')."),
    sa.Column('is_default', sa.Boolean(), nullable=False, comment="Indica se é o contato padrão (campo 'isDefault')."),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp da criação do registro no cache local.'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp da última atualização do registro no cache local.'),
    sa.Column('last_sync_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='Timestamp da última sincronização bem-sucedida com o ERP para este registro.'),
    sa.ForeignKeyConstraint(['person_id'], ['erp_persons.id'], name=op.f('fk_erp_person_contacts_person_id_erp_persons'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_erp_person_contacts')),
    sa.UniqueConstraint('person_id', 'erp_sequence_code', name='uq_person_contact_sequence')
    )
    op.create_index(op.f('ix_erp_person_contacts_last_sync_at'), 'erp_person_contacts', ['last_sync_at'], unique=False)
    op.create_index(op.f('ix_erp_person_contacts_person_id'), 'erp_person_contacts', ['person_id'], unique=False)
    op.create_table('erp_person_emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('erp_sequence_code', sa.Integer(), nullable=True, comment='Código de sequência do email no ERP.'),
    sa.Column('type_name', sa.String(length=50), nullable=True, comment="Tipo do email (campo 'typeName')."),
    sa.Column('email_address', sa.String(length=255), nullable=True, comment="Endereço de email (campo 'email')."),
    sa.Column('is_default', sa.Boolean(), nullable=False, comment="Indica se é o email padrão (campo 'isDefault')."),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp da criação do registro no cache local.'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp da última atualização do registro no cache local.'),
    sa.Column('last_sync_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='Timestamp da última sincronização bem-sucedida com o ERP para este registro.'),
    sa.ForeignKeyConstraint(['person_id'], ['erp_persons.id'], name=op.f('fk_erp_person_emails_person_id_erp_persons'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_erp_person_emails')),
    sa.UniqueConstraint('person_id', 'erp_sequence_code', name='uq_person_email_sequence')
    )
    op.create_index(op.f('ix_erp_person_emails_email_address'), 'erp_person_emails', ['email_address'], unique=False)
    op.create_index(op.f('ix_erp_person_emails_last_sync_at'), 'erp_person_emails', ['last_sync_at'], unique=False)
    op.create_index(op.f('ix_erp_person_emails_person_id'), 'erp_person_emails', ['person_id'], unique=False)
    op.create_table('erp_person_familiars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True, comment="Nome do familiar (campo 'name')."),
    sa.Column('birth_date', sa.Date(), nullable=True, comment="Data de nascimento do familiar (campo 'birthDate')."),
    sa.Column('gender', sa.String(length=20), nullable=True, comment="Gênero do familiar (campo 'gender')."),
    sa.Column('kinship', sa.String(length=50), nullable=True, comment="Parentesco (campo 'kinshipDescription')."),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp da criação do registro no cache local.'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp da última atualização do registro no cache local.'),
    sa.Column('last_sync_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='Timestamp da última sincronização bem-sucedida com o ERP para este registro.'),
    sa.ForeignKeyConstraint(['person_id'], ['erp_persons.id'], name=op.f('fk_erp_person_familiars_person_id_erp_persons'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_erp_person_familiars'))
    )
    op.create_index(op.f('ix_erp_person_familiars_last_sync_at'), 'erp_person_familiars', ['last_sync_at'], unique=False)
    op.create_index(op.f('ix_erp_person_familiars_person_id'), 'erp_person_familiars', ['person_id'], unique=False)
    op.create_table('erp_person_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('erp_sequence_code', sa.Integer(), nullable=True, comment='Código de sequência da observação no ERP.'),
    sa.Column('observation_type', sa.String(length=20), nullable=False, comment="Tipo da Observação: 'General' (de 'observations') ou 'Customer' (de 'customerObservations')."),
    sa.Column('observation_text', sa.Text(), nullable=True, comment="Texto da observação (campo 'observation')."),
    sa.Column('is_maintenance', sa.Boolean(), nullable=True, comment="Flag 'isMaintenance' do ERP."),
    sa.Column('erp_last_change_date', sa.TIMESTAMP(timezone=True), nullable=True, comment="Data da última alteração no ERP (apenas para tipo 'Customer', campo 'LastChangeDate')."),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp da criação do registro no cache local.'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp da última atualização do registro no cache local.'),
    sa.Column('last_sync_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='Timestamp da última sincronização bem-sucedida com o ERP para este registro.'),
    sa.ForeignKeyConstraint(['person_id'], ['erp_persons.id'], name=op.f('fk_erp_person_observations_person_id_erp_persons'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_erp_person_observations')),
    sa.UniqueConstraint('person_id', 'observation_type', 'erp_sequence_code', name='uq_person_observation_sequence')
    )
    op.create_index(op.f('ix_erp_person_observations_last_sync_at'), 'erp_person_observations', ['last_sync_at'], unique=False)
    op.create_index(op.f('ix_erp_person_observations_person_id'), 'erp_person_observations', ['person_id'], unique=False)
    op.create_table('erp_person_partners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('partner_erp_code', sa.Integer(), nullable=False, comment="Código ERP do sócio (campo 'code')."),
    sa.Column('cpf_cnpj', sa.String(length=14), nullable=True, comment="CPF/CNPJ do sócio (campo 'cpfCnpj')."),
    sa.Column('name', sa.Text(), nullable=True, comment="Nome do sócio (campo 'name')."),
    sa.Column('participation_percentage', sa.NUMERIC(precision=5, scale=2), nullable=True, comment="Percentual de participação (campo 'percentageParticipation')."),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp da criação do registro no cache local.'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp da última atualização do registro no cache local.'),
    sa.Column('last_sync_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='Timestamp da última sincronização bem-sucedida com o ERP para este registro.'),
    sa.ForeignKeyConstraint(['person_id'], ['erp_persons.id'], name=op.f('fk_erp_person_partners_person_id_erp_persons'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_erp_person_partners')),
    sa.UniqueConstraint('person_id', 'partner_erp_code', name='uq_person_partner')
    )
    op.create_index(op.f('ix_erp_person_partners_last_sync_at'), 'erp_person_partners', ['last_sync_at'], unique=False)
    op.create_index(op.f('ix_erp_person_partners_partner_erp_code'), 'erp_person_partners', ['partner_erp_code'], unique=False)
    op.create_index(op.f('ix_erp_person_partners_person_id'), 'erp_person_partners', ['person_id'], unique=False)
    op.create_table('erp_person_payment_methods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('erp_payment_method_code', sa.Integer(), nullable=False, comment='Código do método de pagamento aceito pela pessoa no ERP.'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp da criação do registro no cache local.'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp da última atualização do registro no cache local.'),
    sa.Column('last_sync_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='Timestamp da última sincronização bem-sucedida com o ERP para este registro.'),
    sa.ForeignKeyConstraint(['person_id'], ['erp_persons.id'], name=op.f('fk_erp_person_payment_methods_person_id_erp_persons'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_erp_person_payment_methods')),
    sa.UniqueConstraint('person_id', 'erp_payment_method_code', name='uq_person_payment_method')
    )
    op.create_index(op.f('ix_erp_person_payment_methods_last_sync_at'), 'erp_person_payment_methods', ['last_sync_at'], unique=False)
    op.create_index(op.f('ix_erp_person_payment_methods_person_id'), 'erp_person_payment_methods', ['person_id'], unique=False)
    op.create_table('erp_person_phones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('erp_sequence_code', sa.Integer(), nullable=True, comment='Código de sequência do telefone no ERP.'),
    sa.Column('type_name', sa.String(length=50), nullable=True, comment="Tipo do telefone (campo 'typeName')."),
    sa.Column('number', sa.String(length=30), nullable=True, comment="Número do telefone (campo 'number')."),
    sa.Column('extension', sa.String(length=10), nullable=True, comment="Ramal (campo 'branchLine')."),
    sa.Column('is_default', sa.Boolean(), nullable=False, comment="Indica se é o telefone padrão (campo 'isDefault')."),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp da criação do registro no cache local.'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp da última atualização do registro no cache local.'),
    sa.Column('last_sync_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='Timestamp da última sincronização bem-sucedida com o ERP para este registro.'),
    sa.ForeignKeyConstraint(['person_id'], ['erp_persons.id'], name=op.f('fk_erp_person_phones_person_id_erp_persons'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_erp_person_phones')),
    sa.UniqueConstraint('person_id', 'erp_sequence_code', name='uq_person_phone_sequence')
    )
    op.create_index(op.f('ix_erp_person_phones_last_sync_at'), 'erp_person_phones', ['last_sync_at'], unique=False)
    op.create_index(op.f('ix_erp_person_phones_person_id'), 'erp_person_phones', ['person_id'], unique=False)
    op.create_table('erp_person_preferences',
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('payment_condition_code', sa.Integer(), nullable=True, comment="Código da condição de pagamento padrão (campo 'paymentConditionCode')."),
    sa.Column('payment_condition_desc', sa.String(length=100), nullable=True, comment="Descrição da condição de pagamento (campo 'paymentConditionDescription')."),
    sa.Column('shipping_company_code', sa.Integer(), nullable=True, comment="Código da transportadora padrão (campo 'shippingCompanyCode')."),
    sa.Column('shipping_company_name', sa.Text(), nullable=True, comment="Nome da transportadora padrão (campo 'shippingCompanyName')."),
    sa.Column('freight_type', sa.String(length=20), nullable=True, comment="Tipo de frete padrão (campo 'freightType')."),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp da criação do registro no cache local.'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp da última atualização do registro no cache local.'),
    sa.Column('last_sync_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='Timestamp da última sincronização bem-sucedida com o ERP para este registro.'),
    sa.ForeignKeyConstraint(['person_id'], ['erp_persons.id'], name=op.f('fk_erp_person_preferences_person_id_erp_persons'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('person_id', name=op.f('pk_erp_person_preferences'))
    )
    op.create_index(op.f('ix_erp_person_preferences_last_sync_at'), 'erp_person_preferences', ['last_sync_at'], unique=False)
    op.create_table('erp_person_references',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('erp_sequence_code', sa.Integer(), nullable=True, comment='Código de sequência da referência no ERP.'),
    sa.Column('type', sa.String(length=20), nullable=True, comment="Tipo da referência (campo 'type', ex: Banking, Commercial)."),
    sa.Column('description', sa.Text(), nullable=True, comment="Descrição/Nome da referência (campo 'description')."),
    sa.Column('phone_number', sa.String(length=30), nullable=True, comment="Telefone da referência (campo 'phoneNumber')."),
    sa.Column('responsible_name', sa.Text(), nullable=True, comment="Nome do responsável/contato na referência (campo 'responsiblePersonName')."),
    sa.Column('is_inactive', sa.Boolean(), nullable=True, comment="Flag 'isInactive' da referência no ERP."),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp da criação do registro no cache local.'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp da última atualização do registro no cache local.'),
    sa.Column('last_sync_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='Timestamp da última sincronização bem-sucedida com o ERP para este registro.'),
    sa.ForeignKeyConstraint(['person_id'], ['erp_persons.id'], name=op.f('fk_erp_person_references_person_id_erp_persons'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_erp_person_references')),
    sa.UniqueConstraint('person_id', 'erp_sequence_code', name='uq_person_reference_sequence')
    )
    op.create_index(op.f('ix_erp_person_references_last_sync_at'), 'erp_person_references', ['last_sync_at'], unique=False)
    op.create_index(op.f('ix_erp_person_references_person_id'), 'erp_person_references', ['person_id'], unique=False)
    op.create_table('erp_person_related',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('related_erp_code', sa.Integer(), nullable=False, comment="Código ERP da pessoa relacionada (campo 'code')."),
    sa.Column('related_cpf_cnpj', sa.String(length=14), nullable=True, comment="CPF/CNPJ da pessoa relacionada (campo 'cpfCnpj')."),
    sa.Column('related_name', sa.Text(), nullable=True, comment="Nome da pessoa relacionada (campo 'name')."),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp da criação do registro no cache local.'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp da última atualização do registro no cache local.'),
    sa.Column('last_sync_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='Timestamp da última sincronização bem-sucedida com o ERP para este registro.'),
    sa.ForeignKeyConstraint(['person_id'], ['erp_persons.id'], name=op.f('fk_erp_person_related_person_id_erp_persons'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_erp_person_related')),
    sa.UniqueConstraint('person_id', 'related_erp_code', name='uq_person_related_person')
    )
    op.create_index(op.f('ix_erp_person_related_last_sync_at'), 'erp_person_related', ['last_sync_at'], unique=False)
    op.create_index(op.f('ix_erp_person_related_person_id'), 'erp_person_related', ['person_id'], unique=False)
    op.create_index(op.f('ix_erp_person_related_related_erp_code'), 'erp_person_related', ['related_erp_code'], unique=False)
    op.create_table('erp_person_representatives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('representative_erp_code', sa.Integer(), nullable=False, comment="Código ERP do representante (campo 'representativeCode')."),
    sa.Column('cpf_cnpj', sa.String(length=14), nullable=True, comment="CPF/CNPJ do representante (campo 'cpfCnpj')."),
    sa.Column('classification_code', sa.String(length=50), nullable=True, comment="Código da classificação do representante (campo 'classificationCode')."),
    sa.Column('classification_type_code', sa.Integer(), nullable=True, comment="Código do tipo de classificação do representante (campo 'classificationTypeCode')."),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp da criação do registro no cache local.'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp da última atualização do registro no cache local.'),
    sa.Column('last_sync_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='Timestamp da última sincronização bem-sucedida com o ERP para este registro.'),
    sa.ForeignKeyConstraint(['person_id'], ['erp_persons.id'], name=op.f('fk_erp_person_representatives_person_id_erp_persons'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_erp_person_representatives')),
    sa.UniqueConstraint('person_id', 'representative_erp_code', name='uq_person_representative')
    )
    op.create_index(op.f('ix_erp_person_representatives_last_sync_at'), 'erp_person_representatives', ['last_sync_at'], unique=False)
    op.create_index(op.f('ix_erp_person_representatives_person_id'), 'erp_person_representatives', ['person_id'], unique=False)
    op.create_index(op.f('ix_erp_person_representatives_representative_erp_code'), 'erp_person_representatives', ['representative_erp_code'], unique=False)
    op.create_table('erp_person_social_networks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('erp_sequence_code', sa.Integer(), nullable=True, comment='Código de sequência da rede social no ERP.'),
    sa.Column('type_name', sa.String(length=50), nullable=True, comment="Tipo da rede social (campo 'typeName')."),
    sa.Column('address', sa.Text(), nullable=True, comment="Endereço/URL/Handle da rede social (campo 'address')."),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp da criação do registro no cache local.'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp da última atualização do registro no cache local.'),
    sa.Column('last_sync_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='Timestamp da última sincronização bem-sucedida com o ERP para este registro.'),
    sa.ForeignKeyConstraint(['person_id'], ['erp_persons.id'], name=op.f('fk_erp_person_social_networks_person_id_erp_persons'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_erp_person_social_networks')),
    sa.UniqueConstraint('person_id', 'erp_sequence_code', name='uq_person_social_network_sequence')
    )
    op.create_index(op.f('ix_erp_person_social_networks_last_sync_at'), 'erp_person_social_networks', ['last_sync_at'], unique=False)
    op.create_index(op.f('ix_erp_person_social_networks_person_id'), 'erp_person_social_networks', ['person_id'], unique=False)
    op.create_table('erp_person_statistics',
    sa.Column('person_id', sa.Integer(), nullable=False, comment='Chave estrangeira referenciando a pessoa (erp_persons.id).'),
    sa.Column('average_delay', sa.Integer(), nullable=True, comment='Atraso médio em dias (averageDelay).'),
    sa.Column('maximum_delay', sa.Integer(), nullable=True, comment='Atraso máximo em dias (maximumDelay).'),
    sa.Column('purchase_quantity', sa.Integer(), nullable=True, comment='Quantidade de compras (purchaseQuantity).'),
    sa.Column('total_purchase_value', sa.NUMERIC(precision=18, scale=2), nullable=True, comment='Valor total das compras (totalPurchaseValue).'),
    sa.Column('average_purchase_value', sa.NUMERIC(precision=18, scale=2), nullable=True, comment='Valor médio das compras (averagePurchaseValue).'),
    sa.Column('biggest_purchase_date', sa.Date(), nullable=True, comment='Data da maior compra (biggestPurchaseDate).'),
    sa.Column('biggest_purchase_value', sa.NUMERIC(precision=18, scale=2), nullable=True, comment='Valor da maior compra (biggestPurchaseValue).'),
    sa.Column('first_purchase_date', sa.Date(), nullable=True, comment='Data da primeira compra (firstPurchaseDate).'),
    sa.Column('first_purchase_value', sa.NUMERIC(precision=18, scale=2), nullable=True, comment='Valor da primeira compra (firstPurchaseValue).'),
    sa.Column('last_purchase_value', sa.NUMERIC(precision=18, scale=2), nullable=True, comment='Valor da última compra (lastPurchaseValue).'),
    sa.Column('last_purchase_date', sa.Date(), nullable=True, comment='Data da última compra (lastPurchaseDate).'),
    sa.Column('total_installments_paid', sa.NUMERIC(precision=18, scale=2), nullable=True, comment='Valor total das parcelas pagas (totalInstallmentsPaid).'),
    sa.Column('quantity_installments_paid', sa.Integer(), nullable=True, comment='Quantidade de parcelas pagas (quantityInstallmentsPaid).'),
    sa.Column('average_value_installments_paid', sa.NUMERIC(precision=18, scale=2), nullable=True, comment='Valor médio das parcelas pagas (averageValueInstallmentsPaid).'),
    sa.Column('total_installments_delayed', sa.NUMERIC(precision=18, scale=2), nullable=True, comment='Valor total das parcelas atrasadas (totalInstallmentsDelayed).'),
    sa.Column('quantity_installments_delayed', sa.Integer(), nullable=True, comment='Quantidade de parcelas atrasadas (quantityInstallmentsDelayed).'),
    sa.Column('average_installment_delay', sa.NUMERIC(precision=18, scale=2), nullable=True, comment='Atraso médio das parcelas (averageInstallmentDelay).'),
    sa.Column('total_installments_open', sa.NUMERIC(precision=18, scale=2), nullable=True, comment='Valor total das parcelas em aberto (totalInstallmentsOpen).'),
    sa.Column('quantity_installments_open', sa.Integer(), nullable=True, comment='Quantidade de parcelas em aberto (quantityInstallmentsOpen).'),
    sa.Column('average_installments_open', sa.NUMERIC(precision=18, scale=2), nullable=True, comment='Valor médio das parcelas em aberto (averageInstallmentsOpen).'),
    sa.Column('last_invoice_paid_value', sa.NUMERIC(precision=18, scale=2), nullable=True, comment='Valor da última fatura paga (lastInvoicePaidValue).'),
    sa.Column('last_invoice_paid_date', sa.Date(), nullable=True, comment='Data da última fatura paga (lastInvoicePaidDate).'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp da criação do registro no cache local.'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp da última atualização do registro no cache local.'),
    sa.Column('last_sync_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='Timestamp da última sincronização bem-sucedida com o ERP para este registro.'),
    sa.ForeignKeyConstraint(['person_id'], ['erp_persons.id'], name=op.f('fk_erp_person_statistics_person_id_erp_persons'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('person_id', name=op.f('pk_erp_person_statistics'))
    )
    op.create_index(op.f('ix_erp_person_statistics_last_sync_at'), 'erp_person_statistics', ['last_sync_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_erp_person_statistics_last_sync_at'), table_name='erp_person_statistics')
    op.drop_table('erp_person_statistics')
    op.drop_index(op.f('ix_erp_person_social_networks_person_id'), table_name='erp_person_social_networks')
    op.drop_index(op.f('ix_erp_person_social_networks_last_sync_at'), table_name='erp_person_social_networks')
    op.drop_table('erp_person_social_networks')
    op.drop_index(op.f('ix_erp_person_representatives_representative_erp_code'), table_name='erp_person_representatives')
    op.drop_index(op.f('ix_erp_person_representatives_person_id'), table_name='erp_person_representatives')
    op.drop_index(op.f('ix_erp_person_representatives_last_sync_at'), table_name='erp_person_representatives')
    op.drop_table('erp_person_representatives')
    op.drop_index(op.f('ix_erp_person_related_related_erp_code'), table_name='erp_person_related')
    op.drop_index(op.f('ix_erp_person_related_person_id'), table_name='erp_person_related')
    op.drop_index(op.f('ix_erp_person_related_last_sync_at'), table_name='erp_person_related')
    op.drop_table('erp_person_related')
    op.drop_index(op.f('ix_erp_person_references_person_id'), table_name='erp_person_references')
    op.drop_index(op.f('ix_erp_person_references_last_sync_at'), table_name='erp_person_references')
    op.drop_table('erp_person_references')
    op.drop_index(op.f('ix_erp_person_preferences_last_sync_at'), table_name='erp_person_preferences')
    op.drop_table('erp_person_preferences')
    op.drop_index(op.f('ix_erp_person_phones_person_id'), table_name='erp_person_phones')
    op.drop_index(op.f('ix_erp_person_phones_last_sync_at'), table_name='erp_person_phones')
    op.drop_table('erp_person_phones')
    op.drop_index(op.f('ix_erp_person_payment_methods_person_id'), table_name='erp_person_payment_methods')
    op.drop_index(op.f('ix_erp_person_payment_methods_last_sync_at'), table_name='erp_person_payment_methods')
    op.drop_table('erp_person_payment_methods')
    op.drop_index(op.f('ix_erp_person_partners_person_id'), table_name='erp_person_partners')
    op.drop_index(op.f('ix_erp_person_partners_partner_erp_code'), table_name='erp_person_partners')
    op.drop_index(op.f('ix_erp_person_partners_last_sync_at'), table_name='erp_person_partners')
    op.drop_table('erp_person_partners')
    op.drop_index(op.f('ix_erp_person_observations_person_id'), table_name='erp_person_observations')
    op.drop_index(op.f('ix_erp_person_observations_last_sync_at'), table_name='erp_person_observations')
    op.drop_table('erp_person_observations')
    op.drop_index(op.f('ix_erp_person_familiars_person_id'), table_name='erp_person_familiars')
    op.drop_index(op.f('ix_erp_person_familiars_last_sync_at'), table_name='erp_person_familiars')
    op.drop_table('erp_person_familiars')
    op.drop_index(op.f('ix_erp_person_emails_person_id'), table_name='erp_person_emails')
    op.drop_index(op.f('ix_erp_person_emails_last_sync_at'), table_name='erp_person_emails')
    op.drop_index(op.f('ix_erp_person_emails_email_address'), table_name='erp_person_emails')
    op.drop_table('erp_person_emails')
    op.drop_index(op.f('ix_erp_person_contacts_person_id'), table_name='erp_person_contacts')
    op.drop_index(op.f('ix_erp_person_contacts_last_sync_at'), table_name='erp_person_contacts')
    op.drop_table('erp_person_contacts')
    op.drop_index(op.f('ix_erp_person_classifications_person_id'), table_name='erp_person_classifications')
    op.drop_index(op.f('ix_erp_person_classifications_last_sync_at'), table_name='erp_person_classifications')
    op.drop_table('erp_person_classifications')
    op.drop_index(op.f('ix_erp_person_addresses_zip_code'), table_name='erp_person_addresses')
    op.drop_index(op.f('ix_erp_person_addresses_person_id'), table_name='erp_person_addresses')
    op.drop_index(op.f('ix_erp_person_addresses_last_sync_at'), table_name='erp_person_addresses')
    op.drop_table('erp_person_addresses')
    op.drop_index(op.f('ix_erp_person_additional_fields_person_id'), table_name='erp_person_additional_fields')
    op.drop_index(op.f('ix_erp_person_additional_fields_last_sync_at'), table_name='erp_person_additional_fields')
    op.drop_table('erp_person_additional_fields')
    op.drop_index(op.f('ix_erp_legal_entity_details_last_sync_at'), table_name='erp_legal_entity_details')
    op.drop_index(op.f('ix_erp_legal_entity_details_cnpj'), table_name='erp_legal_entity_details')
    op.drop_table('erp_legal_entity_details')
    op.drop_index(op.f('ix_erp_individual_details_last_sync_at'), table_name='erp_individual_details')
    op.drop_index(op.f('ix_erp_individual_details_cpf'), table_name='erp_individual_details')
    op.drop_table('erp_individual_details')
    op.drop_index(op.f('ix_erp_persons_person_type'), table_name='erp_persons')
    op.drop_index(op.f('ix_erp_persons_last_sync_at'), table_name='erp_persons')
    op.drop_index(op.f('ix_erp_persons_is_inactive'), table_name='erp_persons')
    op.drop_index('ix_erp_persons_erp_code_type', table_name='erp_persons')
    op.drop_index(op.f('ix_erp_persons_erp_code'), table_name='erp_persons')
    op.drop_index(op.f('ix_erp_persons_erp_change_date'), table_name='erp_persons')
    op.drop_table('erp_persons')
    # ### end Alembic commands ###
